theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Kolkata

title: Learn with Amit
tagline: Practical AI, LLMs, and RLHF explained simply.
avatar: /assets/img/avatar.png

description: >
  A collection of practical notes, tutorials, and deep dives into AI, Machine Learning, LLMs, RLHF, and Generative AI.

url: "https://amitrai12018.github.io"

github:
  username: amitrai12018

social:
  name: Amit Rai
  email: ankurrai12018@gmail.com
  links:
    - https://github.com/amitrai12018

toc: true

theme_mode:

avatar:

paginate: 10
baseurl: ""

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
